 # Generated by Neurodocker and Reproenv.

FROM debian:bullseye-slim
ENV OS="Linux" \
    PATH="/opt/freesurfer-7.2.0/bin:/opt/freesurfer-7.2.0/fsfast/bin:/opt/freesurfer-7.2.0/tktools:/opt/freesurfer-7.2.0/mni/bin:$PATH" \
    FREESURFER_HOME="/opt/freesurfer-7.2.0" \
    FREESURFER="/opt/freesurfer-7.2.0" \
    SUBJECTS_DIR="/opt/freesurfer-7.2.0/subjects" \
    LOCAL_DIR="/opt/freesurfer-7.2.0/local" \
    FSFAST_HOME="/opt/freesurfer-7.2.0/fsfast" \
    FMRI_ANALYSIS_DIR="/opt/freesurfer-7.2.0/fsfast" \
    FUNCTIONALS_DIR="/opt/freesurfer-7.2.0/sessions" \
    FS_OVERRIDE="0" \
    FIX_VERTEX_AREA="" \
    FSF_OUTPUT_FORMAT="nii.gz# mni env requirements" \
    MINC_BIN_DIR="/opt/freesurfer-7.2.0/mni/bin" \
    MINC_LIB_DIR="/opt/freesurfer-7.2.0/mni/lib" \
    MNI_DIR="/opt/freesurfer-7.2.0/mni" \
    MNI_DATAPATH="/opt/freesurfer-7.2.0/mni/data" \
    MNI_PERL5LIB="/opt/freesurfer-7.2.0/mni/share/perl5" \
    PERL5LIB="/opt/freesurfer-7.2.0/mni/share/perl5"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           libgomp1 \
           libxmu6 \
           libxt6 \
           perl \
           tcsh \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FreeSurfer ..." \
    && mkdir -p /opt/freesurfer-7.2.0 \
    && curl -fL https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.2.0/freesurfer-linux-centos6_x86_64-7.2.0.tar.gz \
    | tar -xz -C /opt/freesurfer-7.2.0 --owner root --group root --no-same-owner --strip-components 1 

ENV FSLDIR="/opt/fsl-6.0.4" \
    PATH="/opt/fsl-6.0.4/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl-6.0.4/bin/fsltclsh" \
    FSLWISH="/opt/fsl-6.0.4/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libopenblas-base \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           nano \
           sudo \
           wget \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FSL ..." \
    && mkdir -p /opt/fsl-6.0.4 \
    && curl -fL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.4-centos6_64.tar.gz \
    | tar -xz -C /opt/fsl-6.0.4 --strip-components 1 \
    && echo "Installing FSL conda environment ..." \
    && bash /opt/fsl-6.0.4/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.4

# Additional code for generating outputs
COPY README.md /opt/fs-extensions/
COPY src /opt/fs-extensions/src

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           mesa-libGLU \
           mesa-dri-drivers \
           java-1.8.0-openjdk \
           openblas-devel \
           ImageMagick \
           xorg-x11-server-Xvfb \
           xorg-x11-xauth \
           which 

# Path
ENV PATHEXT /opt/fs-extensions/src
ENV PATHSYS /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PATH ${PATHEXT}:${PATHSYS}

# add config file script for TRACULA
COPY --chown=501:1590 external/dmri_bids_config /usr/local/freesurfer/bin/dmri_bids_config
RUN chmod 755 /usr/local/freesurfer/bin/dmri_bids_config

# Entrypoint
# ENTRYPOINT ["xwrapper.sh","run_everything.sh"]
ENTRYPOINT ["xwrapper.sh","run_tracula.sh"]
